export const mockProducts = [
          {
            id: "1",
            name: "All-Season Tire",
            slug: "all-season-tire",
            price: 99.99,
            image: "/all-season-tire.png",
            description: "High-quality all-season tire with excellent grip and durability.",
            stock: 25,
          },
          {
            id: "2",
            name: "Winter Tire",
            slug: "winter-tire",
            price: 120.5,
            image: "/winter-tire.png",
            description: "Designed for cold temperatures and snowy conditions.",
            stock: 15,
          },
          {
            id: "3",
            name: "Summer Tire",
            slug: "summer-tire",
            price: 110.0,
            image: "/summer-tire.png",
            description: "Optimized for warm weather with superior handling.",
            stock: 30,
          },
          {
            id: "4",
            name: "Performance Tire",
            slug: "performance-tire",
            price: 150.0,
            image: "/performance-tire.png",
            description: "High-performance tire for sports cars.",
            stock: 10,
          },
          {
            id: "5",
            name: "Off-Road Tire",
            slug: "off-road-tire",
            price: 130.0,
            image: "/off-road-tire.png",
            description: "Rugged tire for extreme off-road conditions.",
            stock: 20,
          },
          {
            id: "6",
            name: "Eco-Friendly Tire",
            slug: "eco-friendly-tire",
            price: 95.0,
            image: "/eco-friendly-tire.png",
            description: "Low rolling resistance for better fuel efficiency.",
            stock: 40,
          },
          {
            id: "7",
            name: "Truck Tire",
            slug: "truck-tire",
            price: 140.0,
            image: "/truck-tire.png",
            description: "Durable and strong, designed for heavy loads.",
            stock: 18,
          },
          {
            id: "8",
            name: "SUV Tire",
            slug: "suv-tire",
            price: 125.0,
            image: "/suv-tire.png",
            description: "Designed for SUVs with enhanced traction.",
            stock: 22,
          },
          {
            id: "9",
            name: "Run-Flat Tire",
            slug: "run-flat-tire",
            price: 160.0,
            image: "/run-flat-tire.png",
            description: "Can be driven on even after a puncture.",
            stock: 12,
          },
          {
            id: "10",
            name: "Touring Tire",
            slug: "touring-tire",
            price: 115.0,
            image: "/touring-tire.png",
            description: "Balanced for comfort and long-distance travel.",
            stock: 28,
          },
          {
            id: "11",
            name: "Mud-Terrain Tire",
            slug: "mud-terrain-tire",
            price: 135.0,
            image: "/mud-terrain-tire.png",
            description: "Designed for extreme mud and rough surfaces.",
            stock: 14,
          },
          {
            id: "12",
            name: "Snow Tire",
            slug: "snow-tire",
            price: 125.0,
            image: "/snow-tire.png",
            description: "Provides superior traction in deep snow.",
            stock: 17,
          },
          {
            id: "13",
            name: "Racing Slicks",
            slug: "racing-slicks",
            price: 200.0,
            image: "/racing-slicks.png",
            description: "Specialized tires for track racing with maximum grip.",
            stock: 8,
          },
          {
            id: "14",
            name: "Hybrid Tire",
            slug: "hybrid-tire",
            price: 105.0,
            image: "/hybrid-tire.png",
            description: "Combines all-season and performance capabilities.",
            stock: 35,
          },
          {
            id: "15",
            name: "Compact Car Tire",
            slug: "compact-car-tire",
            price: 90.0,
            image: "/compact-car-tire.png",
            description: "Designed for small vehicles with efficiency in mind.",
            stock: 50,
          },
        ];
        